name: project-silke-zoospore-tracking
channels:
  - conda-forge
dependencies:
  - cudatoolkit
  - ca-certificates
  - numba
  - openssl
  - pip
  - pip:
      - python_dotenv
      - python-keystoneclient
      - python-swiftclient
      - aicsimageio
      - aicsimageio[nd2]
      - https://github.com/soft-matter/trackpy/archive/refs/tags/v0.6.2rc1.zip
  - python=3.9
  - scikit-image
  - seaborn
  - tqdm
  - zarr
