name: project-silke-zoospore-tracking
channels:
  - conda-forge
dependencies:
  - ca-certificates
  - joblib
  - numba
  - openssl
  - pandas
  - polars=1.2
  - pip:
      - alive-progress
      - bioio
      - bioio-nd2
      - python_dotenv
      - dash
      - dash-bootstrap-components
      - plotly
      # - https://github.com/soft-matter/trackpy/archive/refs/tags/v0.6.2rc1.zip
      - trackpy==0.6.4
  - python=3.10
  - scikit-image
  - seaborn
  - tqdm
  - zarr
