name: project-silke-zoospore-tracking
channels:
  - conda-forge
dependencies:
  # - cudatoolkit
  - ca-certificates
  - dask
  - joblib
  - numba
  - openssl
  - pip:
      - aicsimageio
      - aicsimageio[nd2]
      - https://github.com/soft-matter/trackpy/archive/refs/tags/v0.6.2rc1.zip
  - python=3.10
  - scikit-image
  - seaborn
  - tqdm
  - zarr
